#!/usr/bin/env python3
from argparse import ArgumentParser
from os import execve
from os.path import isabs, abspath, expanduser, basename
from shutil import which
from subprocess import Popen as Subprocess
from os import environ
from hashlib import sha1
from functools import reduce
from sys import stdin, stdout, stderr
from json import load as json_unmarshal, dump as json_marshal
from pwd import getpwnam
from string import Template

backends = [
    "rkt",
    "bwrap"
]
privileged_backends = [
    "rkt"
]
default_backend = "bwrap"

def expand_args(args):
    nargs = args.copy()

    nargs["config"] = abspath(expand(args["config"]))
    return nargs

def expand(v):
    return Template(
        expanduser(
            v
        )
    ).substitute(environ)


def identify(v):
    h = sha1()
    h.update(v.encode("utf8"))
    return h.hexdigest()[:7]

def get_user(user):
    p = getpwnam(user)
    return {
        "user": p.pw_name,
        "uid": p.pw_uid,
        "gid": p.pw_gid
    }

def backend_config_flags(backend, config):
    backend_config = config.get(backend, {})
    user = get_user(environ["USER"])

    def get_mountpoints(config, group):
        return config.get(
            "mountpoints",
            {}
        ).get(
            group,
            []
        )

    def expand_mountpoints(config):
        for k, v in config:
            yield (expand(k), expand(v),)

    def expand_environment(environment):
        res = {}
        for k, v in environment.items():
            res[k] = expand(v)
        return res

    if backend == "rkt":
        def environment_flags(environ):
            return [
                "--set-env={}={}".format(k, v)
                for k, v in environ.items()
            ]

        def mountpoints_flags(mountpoints, rw=True):
            return list(
                reduce(
                    lambda acc, v: acc + [
                        s.format(
                            name=identify(v[0] + " -> " + v[1]),
                            source=v[0],
                            target=v[1],
                            ro=""
                            # FIXME: Imagemagick is notification ready,
                            # otherwise: ",readOnly" if not rw else ""
                        )
                        for s in [
                                "--volume={name},kind=host,source={source}{ro}",
                                "--mount=volume={name},target={target}",
                        ]
                    ],
                    mountpoints,
                    []
                )
            )

        return ["run"] + [
            "--interactive",
            backend_config["container"]
        ] + mountpoints_flags(
            list(
                expand_mountpoints(
                    get_mountpoints(config, "rw")
                )
            ),
            rw=True
        ) + mountpoints_flags(
            list(
                expand_mountpoints(
                    get_mountpoints(config, "ro")
                )
            ),
            rw=False
        ) + environment_flags(
            expand_environment(
                config.get("environment", {})
            )
        ) + environment_flags(
            {
                "DEOMTE_USER": user["user"],
                "DEMOTE_UID": user["uid"],
                "DEMOTE_GID": user["gid"],
                "TERM": environ.get(
                    "TERM",
                    "screen-256color"
                )
            }
        ) + [
            "--dns=208.67.222.222",
            "--net=host"
        ]

    if backend == "bwrap":
        def environment_flags(environ):
            return list(
                reduce(
                    lambda acc, v: acc + v,
                    [
                        ["--setenv", k, v]
                        for k, v in environ.items()
                    ]
                )
            )

        def mountpoints_flags(mountpoints, rw=True):
            return list(
                reduce(
                    lambda acc, v: acc + [
                        s.format(
                            name=identify(v[0] + " -> " + v[1]),
                            source=v[0],
                            target=v[1],
                            ro="ro-" if not rw else ""
                        )
                        for s in ["--{ro}bind", "{source}", "{target}"]
                    ],
                    mountpoints,
                    []
                )
            )

        return [
            "--die-with-parent",
            "--ro-bind",  "/",        "/",
            "--dev-bind", "/dev",     "/dev",
            "--tmpfs",    "/tmp",
            "--tmpfs",    "/run/user/{uid}".format(**user),
            # XXX: This will cause emacs to exit if you press Ctrl-g
            #"--unshare-pid",
            "--unshare-ipc",
            "--unshare-cgroup",
            "--unshare-uts",
            "--hostname", "localhost"
        ] + mountpoints_flags(
            list(
                expand_mountpoints(
                    get_mountpoints(config, "rw")
                )
            ),
            rw=True
        ) + mountpoints_flags(
            list(
                expand_mountpoints(
                    get_mountpoints(config, "ro")
                )
            ),
            rw=False
        ) + environment_flags(
            expand_environment(
                config.get("environment", {})
            )
        ) + environment_flags(
            {
                "TERM": environ.get(
                    "TERM",
                    "screen-256color"
                ),
                "HOME": environ["HOME"]
            }
        ) + [
            "emacs",
            "-nw", "-l", "~/.emacs.d/init.el"
        ]

    return ["--help"]


def commandline_from_config(config):
    backend = config.get(
        "backend",
        default_backend
    )

    return (
        [which("sudo")]
        if backend in privileged_backends
        else []
    ) + [
        which(backend)
    ] + config.get(
        backend,
        {}
    ).get(
        "arguments",
        []
    ) + backend_config_flags(
        backend,
        config
    )

def main(args, rest=[]):
    with open(args["config"], "r") as stream:
        config = json_unmarshal(stream)

    config.update(args)

    commandline = commandline_from_config(config) + \
                  ["--"]               + \
                  rest if len(rest) > 0 else []

    command = commandline[0]
    environment = {
        k: v
        for k, v in environ.items()
        if k.lower().startswith("http_") or \
        k.lower().startswith("https_")
    }

    execve(
        command,
        [basename(command)] + commandline[1:] ,
        environment
    )

if __name__ == "__main__":
    p = ArgumentParser()

    p.add_argument(
        "--backend",
        help="Virtualisation backend to use: {}".format(backends),
        default=default_backend
    )
    p.add_argument(
        "config",
        help="Devcage config file path"
    )

    args, rest = p.parse_known_args()

    main(
        expand_args(
            args.__dict__
        ),
        rest
    )
