#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
if [ -d "$NVM_DIR" ]
then
    if [ -s "$NVM_DIR/nvm.sh" ]
    then
        source "$NVM_DIR/nvm.sh"
    fi

    if [ -s "$NVM_DIR/bash_completion" ] && [[ "$SHELL" == *"/bash" ]]
    then
        source "$NVM_DIR/bash_completion"
    fi
fi
