#!/usr/bin/env bash
set -e

{
    grep "^${DEMOTE_USER}:" /etc/passwd  || echo "${DEMOTE_USER}:x:${DEMOTE_UID}:${DEMOTE_GID}::/home/${DEMOTE_USER}:/usr/bin/zsh" >> /etc/passwd
    grep "^${DEMOTE_USER}:" /etc/group   || echo "$DEMOTE_USER:x:${DEMOTE_GID}:${DEMOTE_USER}"                                   >> /etc/group
    grep "^${DEMOTE_USER} " /etc/sudoers || echo "$DEMOTE_USER ALL=(ALL) NOPASSWD:ALL"                                 >> /etc/sudoers
} > /dev/null 2>&1


chown                       \
    $DEMOTE_UID:$DEMOTE_GID \
    /home/user              \
    /home/user/*            \
    /home/user/.*


export HOME="/home/$DEMOTE_USER"
export USER="$DEMOTE_USER"
export USERNAME="$DEMOTE_USER"
export MAIL="/var/spool/mail/$DEMOTE_USER"
export SHELL="/usr/bin/zsh"

exec /usr/bin/demote             \
    --source=id                  \
    --uid $DEMOTE_UID            \
    --gid $DEMOTE_GID            \
    /usr/bin/emacs               \
    -- -nw -l /home/user/.emacs.d/init.el $@
